#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace VerseAINavigation { struct Ftuple_L_R; }

namespace Blueprint_Paper_VIM { struct FAnimBlueprintGeneratedConstantData; }

namespace EntityCore { class UEntity; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace ButtonStyle_Empty_0 { class UButtonStyle_Empty_C; }

namespace F_MED_Ramirez_Fallback_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace Player_FirstPersonAdditives_AnimBP_Template { struct FAnimBlueprintGeneratedConstantData; }

namespace VerseInput_0 { class U_SolarisSignatureFunctionOuter; }

namespace VerseParameterCollections_0 { class U_SolarisSignatureFunctionOuter; }

namespace VerseMovement_0 { class U_SolarisSignatureFunctionOuter; }

namespace VerseFortniteGameplayAbilities_0 { class U_SolarisSignatureFunctionOuter; }

namespace Player_PropertiesDebug_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Player_RigidBodyPBA_AnimBP_Template { struct FAnimBlueprintGeneratedConstantData; }

namespace ButtonStyle_Empty { class UButtonStyle_Empty_C; }


namespace EpicGamesTemporary_0
{
	struct Ftuple_Lfloat_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lvector3_Mvector3_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lfloat_Mfloat_Mfloat_R;
	struct Ftuple_Lrotation_Mrotation_R;
	struct Ftuple_Lrotation_Mtuple_L_R_Mtuple_L_R_R;
}

namespace Player_TacticalState_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VGameplayRst_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lfloat_Mfloat_R;
	struct Ftuple_Lfloat_Mlogic_R;
	struct Ftuple_Lrotation_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lvector3_M_Kchar_R;
	struct Ftuple_Lvector3_Mvector3_R;
	struct Ftuple_Lvk__component_Many_R;
}

namespace BoarRidingPlayerLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseUI_0
{
	class U_SolarisSignatureFunctionOuter;
	class UUI;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
	struct Ftuple_L_R;
	struct Ftuple_Lany_M_Kchar_R;
	struct Ftuple_Lwidget_Mplayer__ui__slot_R;
}

namespace VerseRestricted
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseAbilities_0
{
	class U_SolarisSignatureFunctionOuter;
	class U_Root;
	struct Ftuple_L_R;
}

namespace Player_DBNO_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_InAir_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_BuildingPose_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_DBNOCarried_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Gameplay_FaceSystem_StateMachine_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_FirstPersonAdditives_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VerseFortniteUI
{
	class UUI;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
	struct Ftuple_L_R;
}

namespace RidingPlayerLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_SourcePose_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VersePrint
{
	class U_Root;
	struct Ftuple_L_Kchar_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_R;
}

namespace Player_LowerBodyJog_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Burt_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace EntityTestSuite
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseSimulation_0
{
	struct Ftuple_Lint_Many_R;
	class U_SolarisSignatureFunctionOuter;
	class USimulation;
	struct Ftuple_L_R;
}

namespace Player_ProceduralAdjustments_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace EpicGamesEngine
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace Execution_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace SwimmingAnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VerseExperimental
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lint_Mint_R;
}

namespace Player_ZipLine_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace MANG_PatrolLayerAnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VerseBasicGameplay
{
	struct Ftuple_Lvector3_M_Kchar_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace Player_ProceduralLayering_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VerseFortnite_0
{
	struct Ftuple_Lentity_Mtuple_L_R_Mtuple_L_R_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_R;
	struct Ftuple_L_R;
	struct Ftuple_Lagent_Mfloat_Mfloat_R;
	struct Ftuple_Lagent_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lfort__character_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lnavigation__target_M_QMovementType_Nmovement__type_20_3d_20_2e_2e_2e_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Ltarget__info_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lteleport__to__result_Mtransform_R;
	struct Ftuple_Lvector3_Mfloat_Mfloat_R;
	struct Ftuple_Lvector3_Mrotation_R;
}

namespace VerseWorldPartition_0
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseEngine_0
{
	struct Ftuple_Lvk__component_Many_R;
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace Component_0
{
	struct Ftuple_L_Kany_Mtuple_L_R_Many_R;
	class U_SolarisSignatureFunctionOuter;
	class U_Root;
	struct Ftuple_L_Kany_Mtuple_L_R_Mint_R;
	struct Ftuple_L_R;
	struct Ftuple_Lwidget_Mplayer__ui__slot_R;
}

namespace VerseNative_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace EpicGamesAssets_0
{
	class UAssets;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace ExecutionTestSuite_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace Verse
{
	struct Ftuple_Lint_Mint_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kany_Mtuple_L_R_Many_R;
	struct Ftuple_L_Kany_Mtuple_L_R_Mint_R;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
	struct Ftuple_L_R;
	struct Ftuple_Lfloat_Mfloat_Mfloat_R;
	struct Ftuple_Lfloat_Mfloat_R;
	struct Ftuple_Lfloat_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lint_Many_R;
	struct Ftuple_Lint_Mint_Mint_R;
}

namespace VerseDevices_0
{
	struct Ftuple_Lrotation_Mrotation_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_R;
	struct Ftuple_L_R;
	struct Ftuple_Lteleport__to__result_Mtransform_R;
	struct Ftuple_Lvector3_Mrotation_R;
	struct Ftuple_Lvector3_Mvector3_R;
}

namespace CompanionAI_0
{
	struct Ftuple_Lvector3_Mvector3_R;
	struct Ftuple_Lnavigation__target_M_QMovementType_Nmovement__type_20_3d_20_2e_2e_2e_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Ltarget__info_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lentity_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_L_Kchar_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_R;
	struct Ftuple_Lagent_Mfloat_Mfloat_R;
	struct Ftuple_Lagent_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lfloat_Mfloat_R;
	struct Ftuple_Lfort__character_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lvector3_M_QRadius_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QNumSegments_Nint_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Lvector3_Mfloat_Mfloat_R;
}

namespace VerseAssets_0
{
	class U_SolarisSignatureFunctionOuter;
	class UAssets;
	struct Ftuple_L_R;
	struct Ftuple_Lany_M_Kchar_R;
}

namespace WolfRidingPlayerLayerAnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Player_Sprint_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Fortnite_M_Avg_Player_AnimBlueprint
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Grandma_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_SkyDiveAndGlide_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_FullBodyAimOffsets_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_LocomotionAdditives_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VerseSimulationMetadata_0
{
	class U_SolarisSignatureFunctionOuter;
	class USimulation;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
}

namespace VerseColors
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lfloat_Mfloat_Mfloat_R;
	struct Ftuple_Lint_Mint_Mint_R;
}

namespace UnrealEngineExperimental_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_R;
	struct Ftuple_Lvector3_M_QRadius_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QNumSegments_Nint_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R;
}

namespace EpicGamesEngineRestricted_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lfloat_Mlogic_R;
}

namespace Entity_0
{
	class U_SolarisSignatureFunctionOuter;
	class U_Root;
	class UEntity;
	struct Ftuple_L_R;
	struct Ftuple_Lentity_Mtuple_L_R_Mtuple_L_R_R;
}

namespace VerseGameplayTags_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseCamera_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseQuery
{
	class U_SolarisSignatureFunctionOuter;
	class U_Root;
	struct Ftuple_L_R;
}

namespace ActorBridgeComponent
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VersePlayspace_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseFortniteInternal
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lint_Mint_R;
}

namespace Player_FreeFlying_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_Goop_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_Land_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
