#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_ButtonStyle_AngledDarkBlueMenuButton

#include "Basic.hpp"

#include "Athena_ButtonStyle_AngledBlueMenuButton_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_ButtonStyle_AngledDarkBlueMenuButton.Athena_ButtonStyle_AngledDarkBlueMenuButton_C
// 0x0000 (0x0730 - 0x0730)
class UAthena_ButtonStyle_AngledDarkBlueMenuButton_C final : public UAthena_ButtonStyle_AngledBlueMenuButton_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Athena_ButtonStyle_AngledDarkBlueMenuButton_C">();
	}
	static class UAthena_ButtonStyle_AngledDarkBlueMenuButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthena_ButtonStyle_AngledDarkBlueMenuButton_C>();
	}
};

}

