#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaRichColorVariantPicker

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaRichColorVariantPicker.AthenaRichColorVariantPicker_C
// 0x0000 (0x0400 - 0x0400)
class UAthenaRichColorVariantPicker_C final : public UFortVariantRichColorPicker
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaRichColorVariantPicker_C">();
	}
	static class UAthenaRichColorVariantPicker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaRichColorVariantPicker_C>();
	}
};

}

