#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_PlayerCameraMode_RespawnedAir

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_PlayerCameraMode_RespawnedAir.Athena_PlayerCameraMode_RespawnedAir_C
// 0x0000 (0x1CD0 - 0x1CD0)
class UAthena_PlayerCameraMode_RespawnedAir_C final : public UFortCameraMode_RespawnedAir
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Athena_PlayerCameraMode_RespawnedAir_C">();
	}
	static class UAthena_PlayerCameraMode_RespawnedAir_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthena_PlayerCameraMode_RespawnedAir_C>();
	}
};

}

