#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaItemTextureVariantPicker

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaItemTextureVariantPicker.AthenaItemTextureVariantPicker_C
// 0x0030 (0x04F0 - 0x04C0)
class UAthenaItemTextureVariantPicker_C final : public UFortVariantItemTexturePicker
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonRichTextBlock*                   TextBlock_AllItemsArchived;                        // 0x04C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_AvailableItems;                     // 0x04D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(bool IsConflicting, class FText ConflictReason)> OnConflictStatusUpdated; // 0x04D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void Construct();
	void ExecuteUbergraph_AthenaItemTextureVariantPicker(int32 EntryPoint);
	void HandleConflictStatusUpdated(bool IsConflicting, const class FText& ConflictReason);
	void HandleEntryInitialized(class UObject* Item, class UUserWidget* Widget);
	void OnToggleAllItemsArchivedMessage(bool bDisplay);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaItemTextureVariantPicker_C">();
	}
	static class UAthenaItemTextureVariantPicker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaItemTextureVariantPicker_C>();
	}
};

}

