#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_ButtonStyle_CollectionTab

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_ButtonStyle_CollectionTab.Athena_ButtonStyle_CollectionTab_C
// 0x0000 (0x0730 - 0x0730)
class UAthena_ButtonStyle_CollectionTab_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Athena_ButtonStyle_CollectionTab_C">();
	}
	static class UAthena_ButtonStyle_CollectionTab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthena_ButtonStyle_CollectionTab_C>();
	}
};

}

