#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_AthenaAlwaysLoadedContentHack

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_AthenaAlwaysLoadedContentHack.B_AthenaAlwaysLoadedContentHack_C
// 0x0028 (0x02B8 - 0x0290)
class AB_AthenaAlwaysLoadedContentHack_C final : public AActor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0290(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class UObject*>                        HardObjectList;                                    // 0x0298(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UClass*>                         HardClassList;                                     // 0x02A8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_AthenaAlwaysLoadedContentHack_C">();
	}
	static class AB_AthenaAlwaysLoadedContentHack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_AthenaAlwaysLoadedContentHack_C>();
	}
};

}

