#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Ground_CameraShake_Heavy

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Ground_CameraShake_Heavy.B_Ground_CameraShake_Heavy_C
// 0x0000 (0x01F0 - 0x01F0)
class UB_Ground_CameraShake_Heavy_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Ground_CameraShake_Heavy_C">();
	}
	static class UB_Ground_CameraShake_Heavy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UB_Ground_CameraShake_Heavy_C>();
	}
};

}

