#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Medium_Explosion_CameraShake

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Medium_Explosion_CameraShake.B_Medium_Explosion_CameraShake_C
// 0x0000 (0x01F0 - 0x01F0)
class UB_Medium_Explosion_CameraShake_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Medium_Explosion_CameraShake_C">();
	}
	static class UB_Medium_Explosion_CameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UB_Medium_Explosion_CameraShake_C>();
	}
};

}

