#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattlePassPageUnlockNotification

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BattlePassPageUnlockNotification.BattlePassPageUnlockNotification_C
// 0x0000 (0x0110 - 0x0110)
class UBattlePassPageUnlockNotification_C final : public UFortUIBattlePassPageUnlockNotification
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BattlePassPageUnlockNotification_C">();
	}
	static class UBattlePassPageUnlockNotification_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBattlePassPageUnlockNotification_C>();
	}
};

}

