#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BladeHazardRuntime

#include "Basic.hpp"


namespace SDK
{

// Enum BladeHazardRuntime.EFortSawBladeSpinningDirection
// NumValues: 0x0004
enum class EFortSawBladeSpinningDirection : uint8
{
	Clockwise                                = 0,
	Counterclockwise                         = 1,
	SnapToCustomDirections                   = 2,
	EFortSawBladeSpinningDirection_MAX       = 3,
};

}

