#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BlueprintDebuggingInterface

#include "Basic.hpp"

#include "BlueprintLogLevel_structs.hpp"


namespace SDK::Params
{

// Function BlueprintDebuggingInterface.BlueprintDebuggingInterface_C.GetBlueprintLogLevel
// 0x0001 (0x0001 - 0x0000)
struct BlueprintDebuggingInterface_C_GetBlueprintLogLevel final
{
public:
	EBlueprintLogLevel                            BlueprintLogLevel;                                 // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

