#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Camera_Shake_Pulse_Flash

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Camera_Shake_Pulse_Flash.BP_Camera_Shake_Pulse_Flash_C
// 0x0000 (0x01F0 - 0x01F0)
class UBP_Camera_Shake_Pulse_Flash_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Camera_Shake_Pulse_Flash_C">();
	}
	static class UBP_Camera_Shake_Pulse_Flash_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Camera_Shake_Pulse_Flash_C>();
	}
};

}

