#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CamShake_BlurPulse

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CamShake_BlurPulse.BP_CamShake_BlurPulse_C
// 0x0000 (0x01F0 - 0x01F0)
class UBP_CamShake_BlurPulse_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CamShake_BlurPulse_C">();
	}
	static class UBP_CamShake_BlurPulse_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CamShake_BlurPulse_C>();
	}
};

}

