#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CameraShake_PortalWarp

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CameraShake_PortalWarp.BP_CameraShake_PortalWarp_C
// 0x0000 (0x01F0 - 0x01F0)
class UBP_CameraShake_PortalWarp_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CameraShake_PortalWarp_C">();
	}
	static class UBP_CameraShake_PortalWarp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CameraShake_PortalWarp_C>();
	}
};

}

