#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FluidSimParent

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_FluidSimParent.BP_FluidSimParent_C.GetNormalRT
// 0x0008 (0x0008 - 0x0000)
struct BP_FluidSimParent_C_GetNormalRT final
{
public:
	class UTextureRenderTarget2D*                 RT;                                                // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

}

