#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GCSteps

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GCSteps.BP_GCSteps_C
// 0x0000 (0x01F0 - 0x01F0)
class UBP_GCSteps_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GCSteps_C">();
	}
	static class UBP_GCSteps_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GCSteps_C>();
	}
};

}

