#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ProjectileTrajectorySplineMesh

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ProjectileTrajectorySplineMesh.BP_ProjectileTrajectorySplineMesh_C
// 0x0000 (0x0710 - 0x0710)
class UBP_ProjectileTrajectorySplineMesh_C final : public USplineMeshComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ProjectileTrajectorySplineMesh_C">();
	}
	static class UBP_ProjectileTrajectorySplineMesh_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ProjectileTrajectorySplineMesh_C>();
	}
};

}

