#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_NonParticipant

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_NonParticipant.BPI_NonParticipant_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_NonParticipant_C final
{
public:
	void AttemptPlayVocalReinforcementSound(const struct FGameplayTagContainer& MetadataTagContainer);
	void PlayVoiceSoundByTag(const struct FGameplayTag& SoundBankTag);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_NonParticipant_C">();
	}
	static class IBPI_NonParticipant_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_NonParticipant_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

}

