#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_Empty

#include "Basic.hpp"

#include "ButtonStyle_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Empty.ButtonStyle-Empty_C
// 0x0000 (0x0730 - 0x0730)
class ButtonStyle_Empty::UButtonStyle_Empty_C final : public UButtonStyle_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BlueprintGeneratedClass ButtonStyle-Empty.ButtonStyle-Empty_C", true, "ButtonStyle-Empty_C">();
	}
	static class ButtonStyle_Empty::UButtonStyle_Empty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ButtonStyle_Empty::UButtonStyle_Empty_C>();
	}
};

}

