#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CommonUIRichTextData

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CommonUIRichTextData.CommonUIRichTextData_C
// 0x0000 (0x0030 - 0x0030)
class UCommonUIRichTextData_C final : public UCommonUIRichTextData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CommonUIRichTextData_C">();
	}
	static class UCommonUIRichTextData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCommonUIRichTextData_C>();
	}
};

}

