#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CompanionAI

#include "Basic.hpp"

#include "FortniteAI_structs.hpp"


namespace SDK::Params
{

// Function CompanionAI.PingComponentData.HandleOnNPCConvertedEvent
// 0x0010 (0x0010 - 0x0000)
struct PingComponentData_HandleOnNPCConvertedEvent final
{
public:
	class AFortPawn*                              InstigatorPawn;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AFortPawn*                              ConvertedPawn;                                     // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CompanionAI.PingComponentData.HandleOnNPCUnconvertedEvent
// 0x0010 (0x0010 - 0x0000)
struct PingComponentData_HandleOnNPCUnconvertedEvent final
{
public:
	class AFortPawn*                              UnconvertedFortPawn;                               // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EUnconvertReason                              UnconvertReason;                                   // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

}

