#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CorrectiveActionDisplayNameScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CorrectiveActionDisplayNameScreen.CorrectiveActionDisplayNameScreen_C
// 0x0018 (0x0440 - 0x0428)
class UCorrectiveActionDisplayNameScreen_C final : public UFortCorrectiveActionDisplayNameScreen
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0428(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_DisplayNameEntrySpinner;                     // 0x0430(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_DisplayNameEntryError;                        // 0x0438(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BndEvt__CorrectiveActionDisplayNameScreen_Button_Continue_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__CorrectiveActionDisplayNameScreen_Button_PrivacyPolicy_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void ExecuteUbergraph_CorrectiveActionDisplayNameScreen(int32 EntryPoint);
	void OnShowCorrectiveActionProcessing(bool bShowProcessing);
	void OnShowDisplayNameDownloading(bool bShowDownloading);
	void OnShowFailureReason(const class FText& FailureReason);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CorrectiveActionDisplayNameScreen_C">();
	}
	static class UCorrectiveActionDisplayNameScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCorrectiveActionDisplayNameScreen_C>();
	}
};

}

