#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CosmeticsFrameworkModifiers

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct CosmeticsFrameworkModifiers.SoftModifierClassPtr
// 0x0020 (0x0020 - 0x0000)
struct FSoftModifierClassPtr final
{
public:
	TSoftClassPtr<class UClass>                   SoftClass;                                         // 0x0000(0x0020)(UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

