#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CowCatcherModCodeRuntime

#include "Basic.hpp"


namespace SDK::Params
{

// Function CowCatcherModCodeRuntime.CowCatcherBarricadeBase.OnPlacementBlockedByPawnChanged
// 0x0001 (0x0001 - 0x0000)
struct CowCatcherBarricadeBase_OnPlacementBlockedByPawnChanged final
{
public:
	bool                                          bBlockedByPawn;                                    // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

