#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CreatorRefreshMyIslandUI

#include "Basic.hpp"


namespace SDK::Params
{

// Function CreatorRefreshMyIslandUI.FortCreativeMyIslandSideNavWidget.SetClearSearchInputEnabled
// 0x0001 (0x0001 - 0x0000)
struct FortCreativeMyIslandSideNavWidget_SetClearSearchInputEnabled final
{
public:
	bool                                          bEnabled;                                          // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CreatorRefreshMyIslandUI.FortCreativeMyIslandSideNavWidget.SetSearchInputEnabled
// 0x0001 (0x0001 - 0x0000)
struct FortCreativeMyIslandSideNavWidget_SetSearchInputEnabled final
{
public:
	bool                                          bEnabled;                                          // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

