#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Creative_Player_PropInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Creative_Player_PropInterface.Creative_Player_PropInterface_C
// 0x0000 (0x0000 - 0x0000)
class ICreative_Player_PropInterface_C final
{
public:
	void PreDestroy();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Creative_Player_PropInterface_C">();
	}
	static class ICreative_Player_PropInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ICreative_Player_PropInterface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

}

