#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CreativeDynamicUIClient

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "SlateCore_structs.hpp"
#include "CreativeDynamicUIRuntime_structs.hpp"


namespace SDK
{

// Class CreativeDynamicUIClient.CreativeDynamicUILibrary
// 0x0000 (0x0028 - 0x0028)
class UCreativeDynamicUILibrary final : public UBlueprintFunctionLibrary
{
public:
	static EHorizontalAlignment GetHorizontalAlignment(const ECreativeDynamicUIAlignment Alignment);
	static EVerticalAlignment GetVerticalAlignment(const ECreativeDynamicUIAlignment Alignment);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CreativeDynamicUILibrary">();
	}
	static class UCreativeDynamicUILibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreativeDynamicUILibrary>();
	}
};

}

