#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CurrencyListViewItem

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CurrencyListViewItem.CurrencyListViewItem_C
// 0x0020 (0x02D8 - 0x02B8)
class UCurrencyListViewItem_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonRichTextBlock*                   CurrencyMessage;                                   // 0x02C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   DisplayMessage;                                    // 0x02C8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void BP_OnEntryReleased();
	void BP_OnItemExpansionChanged(bool bIsExpanded);
	void BP_OnItemSelectionChanged(bool bIsSelected);
	void ExecuteUbergraph_CurrencyListViewItem(int32 EntryPoint);
	void OnListItemObjectSet(class UObject* ListItemObject);
	void SetQuantityAndType(int32 inInt, const class FText& To);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CurrencyListViewItem_C">();
	}
	static class UCurrencyListViewItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurrencyListViewItem_C>();
	}
};

}

