#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CurrencyListView

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CurrencyListView.CurrencyListView_C
// 0x0010 (0x02C8 - 0x02B8)
class UCurrencyListView_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonListView*                        DataListView;                                      // 0x02C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void AddDataToList(const struct FCurrencyData& CurrencyData);
	void ExecuteUbergraph_CurrencyListView(int32 EntryPoint);
	void RunClearListView();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CurrencyListView_C">();
	}
	static class UCurrencyListView_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurrencyListView_C>();
	}
};

}

