#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DelMarCore_Test

#include "Basic.hpp"

#include "DelMarCore_structs.hpp"


namespace SDK::Params
{

// Function DelMarCore_Test.DelMarTestControllerTrackScrubber.ReceiveRaceBeginEvent
// 0x0008 (0x0008 - 0x0000)
struct DelMarTestControllerTrackScrubber_ReceiveRaceBeginEvent final
{
public:
	struct FDelMarEvent_RaceActive                Event;                                             // 0x0000(0x0008)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

}

