#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DelMarSettingsUI

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class DelMarSettingsUI.FortGameSettingRegistryExtension_DelMar
// 0x0000 (0x0028 - 0x0028)
class UFortGameSettingRegistryExtension_DelMar final : public UFortGameSettingRegistryExtension
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortGameSettingRegistryExtension_DelMar">();
	}
	static class UFortGameSettingRegistryExtension_DelMar* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortGameSettingRegistryExtension_DelMar>();
	}
};

}

