#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DirtbikeRuntime

#include "Basic.hpp"

#include "MotorcycleRuntime_classes.hpp"


namespace SDK
{

// Class DirtbikeRuntime.FortDirtbikeVehicle
// 0x0010 (0x2590 - 0x2580)
class AFortDirtbikeVehicle final : public AFortMotorcycleVehicle
{
public:
	uint8                                         Pad_2580[0x10];                                    // 0x2580(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortDirtbikeVehicle">();
	}
	static class AFortDirtbikeVehicle* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFortDirtbikeVehicle>();
	}
};

// Class DirtbikeRuntime.FortDirtbikeVehicleConfigs
// 0x0000 (0x0C50 - 0x0C50)
class UFortDirtbikeVehicleConfigs final : public UFortMotorcycleVehicleConfigs
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortDirtbikeVehicleConfigs">();
	}
	static class UFortDirtbikeVehicleConfigs* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortDirtbikeVehicleConfigs>();
	}
};

}

