#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DynamicAthenaHUD

#include "Basic.hpp"


namespace SDK::Params
{

// Function DynamicAthenaHUD.DynamicAthenaHUDDirector.HandleCreativeQuickbarEquippedChanged
// 0x0001 (0x0001 - 0x0000)
struct DynamicAthenaHUDDirector_HandleCreativeQuickbarEquippedChanged final
{
public:
	bool                                          bIsQuickbarEquipped;                               // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

