#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EliminationBotVFXInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EliminationBotVFXInterface.EliminationBotVFXInterface_C
// 0x0000 (0x0000 - 0x0000)
class IEliminationBotVFXInterface_C final
{
public:
	void EndVFX();
	void TriggerVFX();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EliminationBotVFXInterface_C">();
	}
	static class IEliminationBotVFXInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IEliminationBotVFXInterface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

}

