#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EpicGamesEngineRestricted

#include "Basic.hpp"

#include "EntityActor_classes.hpp"


namespace SDK
{

// Class EpicGamesEngineRestricted.SplineComponentBase
// 0x0000 (0x0088 - 0x0088)
class USplineComponentBase : public UEntityActorComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SplineComponentBase">();
	}
	static class USplineComponentBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USplineComponentBase>();
	}
};

}

