#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EpicMediaCDNHostnames

#include "Basic.hpp"


namespace SDK::Params
{

// Function EpicMediaCDNHostnames.EpicMediaCDNHostnames.GetHostnames
// 0x0010 (0x0010 - 0x0000)
struct EpicMediaCDNHostnames_GetHostnames final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function EpicMediaCDNHostnames.EpicMediaCDNHostnames.GetSelectedHostName
// 0x0010 (0x0010 - 0x0000)
struct EpicMediaCDNHostnames_GetSelectedHostName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

