#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FabricTooltipUI

#include "Basic.hpp"


namespace SDK::Params
{

// Function FabricTooltipUI.FabricTooltipWidget.InitTooltip
// 0x0010 (0x0010 - 0x0000)
struct FabricTooltipWidget_InitTooltip final
{
public:
	class AActor*                                 TargetedActor;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UPrimitiveComponent*                    TargetedComponent;                                 // 0x0008(0x0008)(Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function FabricTooltipUI.FabricTooltipWidget.SetShowMore
// 0x0001 (0x0001 - 0x0000)
struct FabricTooltipWidget_SetShowMore final
{
public:
	bool                                          bShowingMore;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

