#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FabricMetasoundDataTypes

#include "Basic.hpp"


namespace SDK::Params
{

// Function FabricMetasoundDataTypes.FabricMetasoundDrumPlayerSampleBankAsset.GetSampleLabels
// 0x0010 (0x0010 - 0x0000)
struct FabricMetasoundDrumPlayerSampleBankAsset_GetSampleLabels final
{
public:
	TArray<class FText>                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

}

