#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FireMaterialInteractHandler

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FireMaterialInteractHandler.FireMaterialInteractHandler_C
// 0x0000 (0x0090 - 0x0090)
class UFireMaterialInteractHandler_C final : public UFortCurieElementInteractWithMaterialHandlerFire
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FireMaterialInteractHandler_C">();
	}
	static class UFireMaterialInteractHandler_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFireMaterialInteractHandler_C>();
	}
};

}

