#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FireAttachConditionHandler

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FireAttachConditionHandler.FireAttachConditionHandler_C
// 0x0000 (0x0040 - 0x0040)
class UFireAttachConditionHandler_C final : public UFortCurieElementAttachConditionHandlerFire
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FireAttachConditionHandler_C">();
	}
	static class UFireAttachConditionHandler_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFireAttachConditionHandler_C>();
	}
};

}

