#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortWaterAdvanced

#include "Basic.hpp"

#include "WaterAdvanced_classes.hpp"


namespace SDK
{

// Class FortWaterAdvanced.FortShallowWaterSubsystem
// 0x0000 (0x0218 - 0x0218)
class UFortShallowWaterSubsystem final : public UShallowWaterSubsystem
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortShallowWaterSubsystem">();
	}
	static class UFortShallowWaterSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortShallowWaterSubsystem>();
	}
};

}

