#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortPlayerAnimComponentBP

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FortPlayerAnimComponentBP.FortPlayerAnimComponentBP_C
// 0x0000 (0x0F70 - 0x0F70)
class UFortPlayerAnimComponentBP_C final : public UFortPlayerAnimationComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FortPlayerAnimComponentBP_C">();
	}
	static class UFortPlayerAnimComponentBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortPlayerAnimComponentBP_C>();
	}
};

}

