#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortSoundCueTemplates

#include "Basic.hpp"


namespace SDK::Params
{

// Function FortSoundCueTemplates.FortSoundCueTemplateDefaultSettings.GetSettingsForTemplateType
// 0x0010 (0x0010 - 0x0000)
struct FortSoundCueTemplateDefaultSettings_GetSettingsForTemplateType final
{
public:
	TSubclassOf<class UFortSoundCueTemplateBase>  TemplateType;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFortSoundCueTemplateDefaults*          ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function FortSoundCueTemplates.FortSoundCueTemplateSettings.GetDefaultSettingsForTemplateType
// 0x0010 (0x0010 - 0x0000)
struct FortSoundCueTemplateSettings_GetDefaultSettingsForTemplateType final
{
public:
	TSubclassOf<class UFortSoundCueTemplateBase>  TemplateType;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFortSoundCueTemplateDefaults*          ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

