#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortOwningPlayerSocialNameTextBlock

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FortOwningPlayerSocialNameTextBlock.FortOwningPlayerSocialNameTextBlock_C
// 0x0000 (0x02C0 - 0x02C0)
class UFortOwningPlayerSocialNameTextBlock_C final : public UFortOwningPlayerSocialNameTextBlock
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FortOwningPlayerSocialNameTextBlock_C">();
	}
	static class UFortOwningPlayerSocialNameTextBlock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortOwningPlayerSocialNameTextBlock_C>();
	}
};

}

