#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FrontEndSettingsBP

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FrontEndSettingsBP.FrontEndSettingsBP_C
// 0x0008 (0x02B8 - 0x02B0)
class AFrontEndSettingsBP_C final : public AFrontEndSettings
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FrontEndSettingsBP_C">();
	}
	static class AFrontEndSettingsBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFrontEndSettingsBP_C>();
	}
};

}

