#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_BoostJumpPack_Jump

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_BoostJumpPack_Jump.GA_BoostJumpPack_Jump_C
// 0x0000 (0x0B70 - 0x0B70)
class UGA_BoostJumpPack_Jump_C final : public UFortGameplayAbility_Jump
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_BoostJumpPack_Jump_C">();
	}
	static class UGA_BoostJumpPack_Jump_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_BoostJumpPack_Jump_C>();
	}
};

}

