#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameSettingsDetailView

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass GameSettingsDetailView.GameSettingsDetailView_C
// 0x0000 (0x0390 - 0x0390)
class UGameSettingsDetailView_C final : public UFortSettingDetailView
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GameSettingsDetailView_C">();
	}
	static class UGameSettingsDetailView_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameSettingsDetailView_C>();
	}
};

}

