#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Athena_OutsideSafeZone_Stage02

#include "Basic.hpp"

#include "GC_Athena_OutsideSafeZone_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Athena_OutsideSafeZone_Stage02.GC_Athena_OutsideSafeZone_Stage02_C
// 0x0000 (0x0A68 - 0x0A68)
class AGC_Athena_OutsideSafeZone_Stage02_C final : public AGC_Athena_OutsideSafeZone_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Athena_OutsideSafeZone_Stage02_C">();
	}
	static class AGC_Athena_OutsideSafeZone_Stage02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Athena_OutsideSafeZone_Stage02_C>();
	}
};

}

