#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Irwin_PlayerInteraction_LuredInterest

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_Irwin_PlayerInteraction_LuredInterest.GCN_Irwin_PlayerInteraction_LuredInterest_C
// 0x0000 (0x0218 - 0x0218)
class UGCN_Irwin_PlayerInteraction_LuredInterest_C final : public UFortGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_Irwin_PlayerInteraction_LuredInterest_C">();
	}
	static class UGCN_Irwin_PlayerInteraction_LuredInterest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_Irwin_PlayerInteraction_LuredInterest_C>();
	}
};

}

