#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HomerUI

#include "Basic.hpp"


namespace SDK::Params
{

// Function HomerUI.FortHomerComponent.HandleLocalPlayerEliminatedPlayer
// 0x0008 (0x0008 - 0x0000)
struct FortHomerComponent_HandleLocalPlayerEliminatedPlayer final
{
public:
	const class AFortPlayerStateAthena*           Player;                                            // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HomerUI.FortHomerComponent.HandlePawnEmoteStopped
// 0x0010 (0x0010 - 0x0000)
struct FortHomerComponent_HandlePawnEmoteStopped final
{
public:
	const class UFortItemDefinition*              MontageItemDef;                                    // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AFortPawn*                              PawnEmoting;                                       // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

