#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InstancedActors

#include "Basic.hpp"


namespace SDK::Params
{

// Function InstancedActors.InstancedActorsComponent.HasMassEntity
// 0x0001 (0x0001 - 0x0000)
struct InstancedActorsComponent_HasMassEntity final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function InstancedActors.InstancedActorsData.GetManager
// 0x0008 (0x0008 - 0x0000)
struct InstancedActorsData_GetManager final
{
public:
	class AInstancedActorsManager*                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

