#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KeysAndLocksUI

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class KeysAndLocksUI.KeyPlayerInfoWidget
// 0x0028 (0x0348 - 0x0320)
class UKeyPlayerInfoWidget final : public UFortHUDElementWidget
{
public:
	uint8                                         Pad_320[0x8];                                      // 0x0320(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           KeyStatusTag;                                      // 0x0328(0x0004)(Edit, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_32C[0x1C];                                     // 0x032C(0x001C)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void HandleGameplayTagEvent(const struct FGameplayTag& UpdatedTag, int32 TagCount);
	void OnKeyStatusActivated(class AFortPlayerStateAthena* InPlayerState, bool bActivated);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"KeyPlayerInfoWidget">();
	}
	static class UKeyPlayerInfoWidget* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKeyPlayerInfoWidget>();
	}
};

}

