#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LiveLinkHubMessaging

#include "Basic.hpp"

#include "LiveLink_classes.hpp"


namespace SDK
{

// Class LiveLinkHubMessaging.LiveLinkHubMessageBusSourceFactory
// 0x0000 (0x0028 - 0x0028)
class ULiveLinkHubMessageBusSourceFactory final : public ULiveLinkMessageBusSourceFactory
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveLinkHubMessageBusSourceFactory">();
	}
	static class ULiveLinkHubMessageBusSourceFactory* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveLinkHubMessageBusSourceFactory>();
	}
};

}

