#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MidMatchAssignedGameplayRuntime

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "MidMatchAssignedGameplayRuntime_structs.hpp"


namespace SDK::Params
{

// Function MidMatchAssignedGameplayRuntime.FortGameStateComponent_AssignedObjective.CalculateSquadAvgLocation
// 0x0028 (0x0028 - 0x0000)
struct FortGameStateComponent_AssignedObjective_CalculateSquadAvgLocation final
{
public:
	uint8                                         SquadID;                                           // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class UObject*                          WorldContextObject;                                // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                ReturnValue;                                       // 0x0010(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function MidMatchAssignedGameplayRuntime.FortGameStateComponent_AssignedObjective.OnAssignedObjectiveReady
// 0x0028 (0x0028 - 0x0000)
struct FortGameStateComponent_AssignedObjective_OnAssignedObjectiveReady final
{
public:
	struct FFortAssignedObjectiveData             ObjectiveData;                                     // 0x0000(0x0028)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};

}

