#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MotorboatUI

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class MotorboatUI.FortAthenaVehicleDashboardWidget_Meatball
// 0x0000 (0x0588 - 0x0588)
class UFortAthenaVehicleDashboardWidget_Meatball final : public UFortAthenaVehicleDashboardWidget
{
public:
	class AFortMeatballVehicle* GetMeatballVehicle() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortAthenaVehicleDashboardWidget_Meatball">();
	}
	static class UFortAthenaVehicleDashboardWidget_Meatball* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortAthenaVehicleDashboardWidget_Meatball>();
	}
};

}

