#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MotorboatUI

#include "Basic.hpp"


namespace SDK::Params
{

// Function MotorboatUI.FortAthenaVehicleDashboardWidget_Meatball.GetMeatballVehicle
// 0x0008 (0x0008 - 0x0000)
struct FortAthenaVehicleDashboardWidget_Meatball_GetMeatballVehicle final
{
public:
	class AFortMeatballVehicle*                   ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

