#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NitroBarrelRuntime

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"


namespace SDK
{

// ScriptStruct NitroBarrelRuntime.BuildingGameplayActorNitroBarrelClassData
// 0x0000 (0x0118 - 0x0118)
struct FBuildingGameplayActorNitroBarrelClassData final : public FBuildingGameplayActorClassData
{
};

}

