#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NitroGameplayRuntime

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"


namespace SDK
{

// ScriptStruct NitroGameplayRuntime.FortMovementMode_NitroPlayerStateCreationData
// 0x0000 (0x0008 - 0x0008)
struct FFortMovementMode_NitroPlayerStateCreationData final : public FFortMovementMode_BaseExtCreationData
{
};

}

