#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerformanceCaptureCore

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK
{

// ScriptStruct PerformanceCaptureCore.RetargetAnimInstanceProxy
// 0x0010 (0x0760 - 0x0750)
struct FRetargetAnimInstanceProxy final : public FAnimInstanceProxy
{
public:
	uint8                                         Pad_748[0x18];                                     // 0x0748(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

}

