#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PreExplodeRampType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum PreExplodeRampType.PreExplodeRampType
// NumValues: 0x0005
enum class EPreExplodeRampType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator3                           = 2,
	NewEnumerator2                           = 3,
	PreExplodeRampType_MAX                   = 4,
};

}

