#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PressAnyKey

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PressAnyKey.PressAnyKey_C
// 0x0000 (0x05C0 - 0x05C0)
class UPressAnyKey_C final : public UFortSettingsPressAnyKey
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PressAnyKey_C">();
	}
	static class UPressAnyKey_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPressAnyKey_C>();
	}
};

}

