#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SaveTheWorldRuntime

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class SaveTheWorldRuntime.FortSTWUIDataBase
// 0x0000 (0x0030 - 0x0030)
class UFortSTWUIDataBase : public UPrimaryDataAsset
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortSTWUIDataBase">();
	}
	static class UFortSTWUIDataBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortSTWUIDataBase>();
	}
};

}

