#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SettingsPanel

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SettingsPanel.SettingsPanel_C
// 0x0000 (0x0828 - 0x0828)
class USettingsPanel_C final : public UFortSettingsPanel
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SettingsPanel_C">();
	}
	static class USettingsPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USettingsPanel_C>();
	}
};

}

