#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SimpleMaterialProgressBar

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SimpleMaterialProgressBar.SimpleMaterialProgressBar_C
// 0x0000 (0x03B0 - 0x03B0)
class USimpleMaterialProgressBar_C final : public UFortSimpleMaterialProgressBar
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SimpleMaterialProgressBar_C">();
	}
	static class USimpleMaterialProgressBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USimpleMaterialProgressBar_C>();
	}
};

}

