#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SnowSurfaceCoverageMap_GSC

#include "Basic.hpp"

#include "SpecialSurfaceCoverageRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SnowSurfaceCoverageMap_GSC.SnowSurfaceCoverageMap_GSC_C
// 0x0000 (0x0110 - 0x0110)
class USnowSurfaceCoverageMap_GSC_C final : public UFortGameStateComponent_SurfaceCoverageMap
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SnowSurfaceCoverageMap_GSC_C">();
	}
	static class USnowSurfaceCoverageMap_GSC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USnowSurfaceCoverageMap_GSC_C>();
	}
};

}

