#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SparksCoreUI

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct SparksCoreUI.SparksQuestScreenToggleEvent
// 0x0001 (0x0001 - 0x0000)
struct FSparksQuestScreenToggleEvent final
{
public:
	uint8                                         Pad_0[0x1];                                        // 0x0000(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

}

