#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SqueegeeInjectionSlot

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SqueegeeInjectionSlot.SqueegeeInjectionSlot_C
// 0x0000 (0x0328 - 0x0328)
class USqueegeeInjectionSlot_C final : public UFortSqueegeeWidgetInjectionSlot
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SqueegeeInjectionSlot_C">();
	}
	static class USqueegeeInjectionSlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USqueegeeInjectionSlot_C>();
	}
};

}

