#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StreamingRadio

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class StreamingRadio.StreamingRadioManagerNative
// 0x0010 (0x02A0 - 0x0290)
class AStreamingRadioManagerNative final : public AActor
{
public:
	class UFortStreamMediaSource*                 StreamMediaSource;                                 // 0x0290(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UMediaPlayer*                           MediaPlayer;                                       // 0x0298(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"StreamingRadioManagerNative">();
	}
	static class AStreamingRadioManagerNative* GetDefaultObj()
	{
		return GetDefaultObjImpl<AStreamingRadioManagerNative>();
	}
};

}

