#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_VEH_Windows

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Struct_VEH_Windows.Struct_VEH_Windows
// 0x0020 (0x0020 - 0x0000)
struct FStruct_VEH_Windows final
{
public:
	TSoftObjectPtr<class UMaterialInstanceConstant> Window_23_9242D84D446944DD0D7D739136E38C28;      // 0x0000(0x0020)(Edit, BlueprintVisible, HasGetValueTypeHash)
};

}

