#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SunRoseEnvGameplayRuntime

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"


namespace SDK::Params
{

// Function SunRoseEnvGameplayRuntime.FortChargingSet_SunroseDash.OnRep_CurrentCharges
// 0x0028 (0x0028 - 0x0000)
struct FortChargingSet_SunroseDash_OnRep_CurrentCharges final
{
public:
	struct FFortGameplayAttributeData             OldValue;                                          // 0x0000(0x0028)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};

}

