#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SunRoseChainWhipGameplay

#include "Basic.hpp"


namespace SDK::Params
{

// Function SunRoseChainWhipGameplay.FortCheatManager_SunRoseChainWhip.SunRoseApplyHookShot
// 0x0004 (0x0004 - 0x0000)
struct FortCheatManager_SunRoseChainWhip_SunRoseApplyHookShot final
{
public:
	float                                         Delay;                                             // 0x0000(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

