#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SurfaceEffects

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK
{

// ScriptStruct SurfaceEffects.SurfaceEffectTableRow
// 0x0008 (0x0010 - 0x0008)
struct FSurfaceEffectTableRow final : public FTableRowBase
{
public:
	class USurfaceEffectRule*                     Rule;                                              // 0x0008(0x0008)(Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

