#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TacOvershieldUI

#include "Basic.hpp"


namespace SDK::Params
{

// Function TacOvershieldUI.TacOvershieldPlayerInfoWidget.OnOvershieldStateChanged
// 0x0008 (0x0008 - 0x0000)
struct TacOvershieldPlayerInfoWidget_OnOvershieldStateChanged final
{
public:
	float                                         Overshield;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OvershieldMax;                                     // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function TacOvershieldUI.TacOvershieldPlayerInfoWidget.OnPlayerStateSet
// 0x0008 (0x0008 - 0x0000)
struct TacOvershieldPlayerInfoWidget_OnPlayerStateSet final
{
public:
	class AFortPlayerStateAthena*                 InPlayerState;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

