#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TankRuntime

#include "Basic.hpp"


namespace SDK::Params
{

// Function TankRuntime.FortTankVehicleAnimInstance.UpdateMIDEngineProperties
// 0x0008 (0x0008 - 0x0000)
struct FortTankVehicleAnimInstance_UpdateMIDEngineProperties final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         EngineHealthRatio;                                 // 0x0004(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function TankRuntime.FortTankVehicleAudioController.GetTankVehicleActor
// 0x0008 (0x0008 - 0x0000)
struct FortTankVehicleAudioController_GetTankVehicleActor final
{
public:
	class AFortTankVehicle*                       ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

