#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UEFN_TextBlock

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UEFN_TextBlock.UEFN_TextBlock_C
// 0x0000 (0x0330 - 0x0330)
class UUEFN_TextBlock_C final : public UUEFNTextBlockBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UEFN_TextBlock_C">();
	}
	static class UUEFN_TextBlock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUEFN_TextBlock_C>();
	}
};

}

