#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIChartRuntime

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class UIChartRuntime.UIChartGlobals
// 0x0000 (0x0028 - 0x0028)
class UUIChartGlobals final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UIChartGlobals">();
	}
	static class UUIChartGlobals* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIChartGlobals>();
	}
};

}

