#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VaultSceneSinglePedestal

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass VaultSceneSinglePedestal.VaultSceneSinglePedestal_C
// 0x0000 (0x0378 - 0x0378)
class AVaultSceneSinglePedestal_C final : public AItemPreviewScene
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VaultSceneSinglePedestal_C">();
	}
	static class AVaultSceneSinglePedestal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVaultSceneSinglePedestal_C>();
	}
};

}

