#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VehicleModsUI

#include "Basic.hpp"


namespace SDK::Params
{

// Function VehicleModsUI.AthenaMarkerDetailsExtensionVehicleMods.SetModInfo
// 0x0008 (0x0008 - 0x0000)
struct AthenaMarkerDetailsExtensionVehicleMods_SetModInfo final
{
public:
	const class UFortVehicleModConfig*            VehicleModConfig;                                  // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function VehicleModsUI.FortInteractionContextInfoWidgetVehicleMods.HandleContextInfoUpdated
// 0x0008 (0x0008 - 0x0000)
struct FortInteractionContextInfoWidgetVehicleMods_HandleContextInfoUpdated final
{
public:
	class UFortInteractContextInfo*               ContextInfo;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function VehicleModsUI.FortInteractionContextInfoWidgetVehicleMods.SetModInfo
// 0x0008 (0x0008 - 0x0000)
struct FortInteractionContextInfoWidgetVehicleMods_SetModInfo final
{
public:
	const class UFortVehicleModConfig*            VehicleModConfig;                                  // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

