#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseRestricted

#include "Basic.hpp"


namespace SDK
{

// VerseStruct VerseRestricted.tuple_L_R
// 0x0001 (0x0001 - 0x0000)
struct VerseRestricted::Ftuple_L_R final
{
public:
	uint8                                         _StructPaddingDummy;                               // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

