#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseAIBase

#include "Basic.hpp"


namespace SDK
{

// VerseStruct VerseAIBase.VerseAIBase_dummy_verse_ai_base
// 0x0001 (0x0001 - 0x0000)
struct FVerseAIBase_dummy_verse_ai_base final
{
public:
	uint8                                         _StructPaddingDummy;                               // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

