#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseAbilities

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "NetCore_structs.hpp"


namespace SDK
{

// ScriptStruct VerseAbilities.VerseAbilityMapping
// 0x000C (0x0018 - 0x000C)
struct FVerseAbilityMapping final : public FFastArraySerializerItem
{
public:
	struct FGameplayAbilitySpecHandle             Handle;                                            // 0x000C(0x0004)(NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UVerseAbility*                          AbilityArchetype;                                  // 0x0010(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct VerseAbilities.VerseAbilityMappingContainer
// 0x0010 (0x0118 - 0x0108)
struct FVerseAbilityMappingContainer final : public FFastArraySerializer
{
public:
	TArray<struct FVerseAbilityMapping>           Items;                                             // 0x0108(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
};

}

