#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseSimulation

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK
{

// ScriptStruct VerseSimulation.LocalizableMessageParameterAgent
// 0x0038 (0x0038 - 0x0000)
struct FLocalizableMessageParameterAgent final
{
public:
	struct FUniqueNetIdRepl                       Value;                                             // 0x0000(0x0030)(HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint64                                        PawnNetGuid;                                       // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

