#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VersePlayspace_0

#include "Basic.hpp"


namespace SDK
{

// VerseEnum VersePlayspace.Playspace_PlayerType
// NumValues: 0x0004
enum class EPlayspace_PlayerType : uint8
{
	All                                      = 0,
	ActivePlayer                             = 1,
	Spectator                                = 2,
	Playspace_MAX                            = 3,
};

// VerseStruct VersePlayspace.tuple_L_R
// 0x0001 (0x0001 - 0x0000)
struct VersePlayspace_0::Ftuple_L_R final
{
public:
	uint8                                         _StructPaddingDummy;                               // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

