#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VKDownloadOnDemandGameplay

#include "Basic.hpp"


namespace SDK::Params
{

// Function VKDownloadOnDemandGameplay.DownloadOnDemandComponent.HandleMnemonicsFromValkyriePaletteProviderReceived
// 0x0010 (0x0010 - 0x0000)
struct DownloadOnDemandComponent_HandleMnemonicsFromValkyriePaletteProviderReceived final
{
public:
	TArray<class FString>                         Mnemonics;                                         // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};

}

