#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VKPlayRuntime

#include "Basic.hpp"

#include "GameFeatures_classes.hpp"


namespace SDK
{

// Class VKPlayRuntime.FortVKPlayGameFeatureAction_RegisterContentErrorHandler
// 0x0000 (0x0028 - 0x0028)
class UFortVKPlayGameFeatureAction_RegisterContentErrorHandler final : public UGameFeatureAction
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortVKPlayGameFeatureAction_RegisterContentErrorHandler">();
	}
	static class UFortVKPlayGameFeatureAction_RegisterContentErrorHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortVKPlayGameFeatureAction_RegisterContentErrorHandler>();
	}
};

}

