#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VoiceRep

#include "Basic.hpp"

#include "VoiceRep_structs.hpp"


namespace SDK::Params
{

// Function VoiceRep.FortVoiceReportIntroModal.UpdateVisuals
// 0x0001 (0x0001 - 0x0000)
struct FortVoiceReportIntroModal_UpdateVisuals final
{
public:
	EUFortVoiceReportIntroModalType               DescriptionType;                                   // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

