#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WaterMaterialInteractHandler

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WaterMaterialInteractHandler.WaterMaterialInteractHandler_C
// 0x0000 (0x00A0 - 0x00A0)
class UWaterMaterialInteractHandler_C final : public UFortCurieElementInteractWithMaterialHandlerWater
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WaterMaterialInteractHandler_C">();
	}
	static class UWaterMaterialInteractHandler_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWaterMaterialInteractHandler_C>();
	}
};

}

