#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UIKit_Button_Loud

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_UIKit_Button_Loud.WBP_UIKit_Button_Loud_C.ExecuteUbergraph_WBP_UIKit_Button_Loud
// 0x0004 (0x0004 - 0x0000)
struct WBP_UIKit_Button_Loud_C_ExecuteUbergraph_WBP_UIKit_Button_Loud final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

