#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UIKit_StoreSelectionButton

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_UIKit_StoreSelectionButton.WBP_UIKit_StoreSelectionButton_C.ExecuteUbergraph_WBP_UIKit_StoreSelectionButton
// 0x0008 (0x0008 - 0x0000)
struct WBP_UIKit_StoreSelectionButton_C_ExecuteUbergraph_WBP_UIKit_StoreSelectionButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function WBP_UIKit_StoreSelectionButton.WBP_UIKit_StoreSelectionButton_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_UIKit_StoreSelectionButton_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

