#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UIKit_Backplate

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WBP_UIKit_Backplate_Base_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_UIKit_Backplate.WBP_UIKit_Backplate_C
// 0x0008 (0x0338 - 0x0330)
class UWBP_UIKit_Backplate_C final : public UWBP_UIKit_Backplate_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_UIKit_Backplate_C;              // 0x0330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_UIKit_Backplate(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_UIKit_Backplate_C">();
	}
	static class UWBP_UIKit_Backplate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UIKit_Backplate_C>();
	}
};

}

