#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WolfCodeRuntime

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// Class WolfCodeRuntime.FortCheatManager_Wolf
// 0x0000 (0x0028 - 0x0028)
class UFortCheatManager_Wolf final : public UChildCheatManager
{
public:
	void WolfEnable(const bool bEnable);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortCheatManager_Wolf">();
	}
	static class UFortCheatManager_Wolf* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortCheatManager_Wolf>();
	}
};

}

