#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WorldLightingMenu

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WorldLightingMenu.WorldLightingMenu_C
// 0x0000 (0x02A8 - 0x02A8)
class AWorldLightingMenu_C final : public AFortLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WorldLightingMenu_C">();
	}
	static class AWorldLightingMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWorldLightingMenu_C>();
	}
};

}

